/*
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.ui.tests;

import com.google.inject.Injector;
import fi.tucs.entities.ui.internal.EntitiesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EntitiesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntitiesActivator.getInstance().getInjector("fi.tucs.entities.Entities");
	}

}
