/**
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities;

import fi.tucs.entities.AbstractEntitiesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
