/*
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.ide

import com.google.inject.Guice
import fi.tucs.entities.EntitiesRuntimeModule
import fi.tucs.entities.EntitiesStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class EntitiesIdeSetup extends EntitiesStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new EntitiesRuntimeModule, new EntitiesIdeModule))
	}
	
}
