/**
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.entities.impl;

import fi.tucs.entities.entities.EntitiesPackage;
import fi.tucs.entities.entities.PrintStatement;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Print Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrintStatementImpl extends StatementImpl implements PrintStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrintStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntitiesPackage.Literals.PRINT_STATEMENT;
  }

} //PrintStatementImpl
