/**
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.ide;

import fi.tucs.entities.ide.AbstractEntitiesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EntitiesIdeModule extends AbstractEntitiesIdeModule {
}
