/**
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.entities;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignment Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fi.tucs.entities.entities.AssignmentStatement#getAssignee <em>Assignee</em>}</li>
 * </ul>
 *
 * @see fi.tucs.entities.entities.EntitiesPackage#getAssignmentStatement()
 * @model
 * @generated
 */
public interface AssignmentStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Assignee</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assignee</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignee</em>' reference.
   * @see #setAssignee(Field)
   * @see fi.tucs.entities.entities.EntitiesPackage#getAssignmentStatement_Assignee()
   * @model
   * @generated
   */
  Field getAssignee();

  /**
   * Sets the value of the '{@link fi.tucs.entities.entities.AssignmentStatement#getAssignee <em>Assignee</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignee</em>' reference.
   * @see #getAssignee()
   * @generated
   */
  void setAssignee(Field value);

} // AssignmentStatement
