/**
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.entities;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fi.tucs.entities.entities.EntityType#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see fi.tucs.entities.entities.EntitiesPackage#getEntityType()
 * @model
 * @generated
 */
public interface EntityType extends FieldType
{
  /**
   * Returns the value of the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' reference.
   * @see #setEntity(Entity)
   * @see fi.tucs.entities.entities.EntitiesPackage#getEntityType_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link fi.tucs.entities.entities.EntityType#getEntity <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' reference.
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

} // EntityType
