/**
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.entities;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fi.tucs.entities.entities.EntitiesPackage#getFieldType()
 * @model
 * @generated
 */
public interface FieldType extends EObject
{
} // FieldType
