/**
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.entities;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fi.tucs.entities.entities.FieldRef#getField <em>Field</em>}</li>
 * </ul>
 *
 * @see fi.tucs.entities.entities.EntitiesPackage#getFieldRef()
 * @model
 * @generated
 */
public interface FieldRef extends Expression
{
  /**
   * Returns the value of the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Field</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' reference.
   * @see #setField(Field)
   * @see fi.tucs.entities.entities.EntitiesPackage#getFieldRef_Field()
   * @model
   * @generated
   */
  Field getField();

  /**
   * Sets the value of the '{@link fi.tucs.entities.entities.FieldRef#getField <em>Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' reference.
   * @see #getField()
   * @generated
   */
  void setField(Field value);

} // FieldRef
