/**
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.entities;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fi.tucs.entities.entities.EntitiesPackage#getPrintStatement()
 * @model
 * @generated
 */
public interface PrintStatement extends Statement
{
} // PrintStatement
