/*
 * generated by Xtext 2.12.0
 */
package fi.tucs.entities.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntitiesScopeProvider extends DelegatingScopeProvider {
}
